### ISSUE TITLE
global variable failed in multiprocess task

### ISSUE THREAD

**Issue by mao-zhou** [IIIS-Li-Group/OpenFE#1]
I run the sample code of california housing, and get this error. I am on Windows platform.

It appears that the code global _data don't work.....

data_temp = _data.loc[train_idx + val_idx]
NameError: name '_data' is not defined

**Comment by ZhangTP1996** [comment]
> I run the sample code of california housing, and get this error. I am on Windows platform.
> 
> It appears that the code global _data don't work.....
> 
> data_temp = _data.loc[train_idx + val_idx] NameError: name '_data' is not defined

What python version are you using? This way of multi-processing requires python version >=3.8

**Comment by mao-zhou** [comment]
Yep, my python version is 3.8.3, I think the requirement is fulfilled

**Comment by summerTony9** [comment]
same issue
UnboundLocalError: local variable 'candidate_feature' referenced before assignment

**Comment by ZhangTP1996** [comment]
> Yep, my python version is 3.8.3, I think the requirement is fulfilled

It seems that the problem is on Windows platform. This way of multi-processing can only run on Linux. We will try to find another way for multiprocessing so that it supports both Linux and Windows. We will inform you when the bug is fixed (probably in one or two days).

**Comment by ZhangTP1996** [comment]
> same issue UnboundLocalError: local variable 'candidate_feature' referenced before assignment

Are you using the Windows platform too? We just find out that our codes can only run on Linux platforms. We will try to find another way for multiprocessing so that it supports both Linux and Windows. We will inform you when the bug is fixed (probably in one or two days).

**Comment by summerTony9** [comment]
i have mac with m1 chip and linux with intel chip.Both have the same issue.

**Comment by LXlearning** [comment]
I have the same problem about ```local variable 'candidate_feature' referenced before assignment```with Mac.

**Comment by mao-zhou** [comment]
Thx TP!

**Comment by ZhangTP1996** [comment]
> I run the sample code of california housing, and get this error. I am on Windows platform.
> 
> It appears that the code global _data don't work.....
> 
> data_temp = _data.loc[train_idx + val_idx] NameError: name '_data' is not defined

The updated latest version should solve your problem. Could you please try
```
pip uninstall openfe
pip install openfe
```
and tell me whether your problem is solved?

**Comment by ZhangTP1996** [comment]
> I have the same problem about `local variable 'candidate_feature' referenced before assignment`with Mac.

The updated latest version should solve your problem. Could you please try
```
pip uninstall openfe
pip install openfe
```
and tell me whether your problem is solved?

**Comment by mao-zhou** [comment]
OK, it works, Cheers!
