### ISSUE TITLE
how to generate OpenFE feature when doing prediction?

### ISSUE THREAD

**Issue by zhxgigi** [IIIS-Li-Group/OpenFE#10]
Hi, 
Once we have a new model based on OpenFE feature, how to transform a new raw data array to OpenFE feature for further prediction task?
Thanks.

**Comment by ZhangTP1996** [comment]
> Hi, Once we have a new model based on OpenFE feature, how to transform a new raw data array to OpenFE feature for further prediction task? Thanks.

Please see the example (https://github.com/IIIS-Li-Group/OpenFE/blob/master/examples/california_housing.py). You can transform the test dataset (new raw data) together with the training dataset using the `transform` function.

**Comment by zhxgigi** [comment]
> 

noted, thank you.

**Comment by zhxgigi** [comment]
noted, thank you.
