### ISSUE TITLE
why number of features calculated per process divided by 4

### ISSUE THREAD

**Issue by uhomelee** [IIIS-Li-Group/OpenFE#11]
A line of code like this in ```_calculate_and_evaluate```function, ```length = int(np.ceil(len(candidate_features) / self.n_jobs / 4))``` .
But in per process, the score calculated by LGBM uses only one core ```n_jobs=1``` in ```_evaluate``` fuction. So is there a specific meaning to the divisor 4?

**Comment by ZhangTP1996** [comment]
If the number of features calculated per process is `length = int(np.ceil(len(candidate_features) / self.n_jobs)`, then the time gap between the first finished process and the last finished process may be large. There isn't a specific meaning to the divisor 4, it is simply a heuristic choice that I think may save some running time.
