### ISSUE TITLE
SystemExit: None

### ISSUE THREAD

**Issue by ruler611** [IIIS-Li-Group/OpenFE#12]
When I tried openFE, the error I got as below.
n_jobs = 4
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2, random_state=1)
ofe = openfe()
ofe.fit(data=X_train,label=y_train, n_jobs=n_jobs)
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "E:\ml\lib\site-packages\openfe\openfe.py", line 676, in _calculate_and_evaluate_multiprocess
    init_metric = self.get_init_metric(val_init, val_y)
  File "E:\ml\lib\site-packages\openfe\openfe.py", line 545, in get_init_metric
    init_metric = log_loss(label, scipy.special.softmax(pred, axis=1))
  File "E:\ml\lib\site-packages\sklearn\metrics\_classification.py", line 2424, in log_loss
    raise ValueError(
ValueError: y_true and y_pred contain different number of classes 9, 10. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [ 1  3  4  5  6  7  8  9 10]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ml\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "E:\ml\lib\site-packages\openfe\openfe.py", line 684, in _calculate_and_evaluate_multiprocess
    exit()
  File "E:\ml\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
"""

The above exception was the direct cause of the following exception:

SystemExit                                Traceback (most recent call last)
<timed exec> in <module>

E:\ml\lib\site-packages\openfe\openfe.py in fit(self, data, label, task, train_index, val_index, candidate_features_list, init_scores, categorical_features, metric, drop_columns, n_data_blocks, min_candidate_features, feature_boosting, stage1_metric, stage2_metric, stage2_params, is_stage1, n_repeats, tmp_save_path, n_jobs, seed, verbose)
    297         self.myprint(f"The number of candidate features is {len(self.candidate_features_list)}")
    298         self.myprint("Start stage I selection.")
--> 299         self.candidate_features_list = self.stage1_select()
    300         self.myprint(f"The number of remaining candidate features is {len(self.candidate_features_list)}")
    301         self.myprint("Start stage II selection.")

E:\ml\lib\site-packages\openfe\openfe.py in stage1_select(self, ratio)
    459         val_idx = val_index_samples[idx]
    460         idx += 1
--> 461         results = self._calculate_and_evaluate(self.candidate_features_list, train_idx, val_idx)
    462         candidate_features_scores = sorted(results, key=lambda x: x[1], reverse=True)
    463         candidate_features_scores = self.delete_same(candidate_features_scores)

E:\ml\lib\site-packages\openfe\openfe.py in _calculate_and_evaluate(self, candidate_features, train_idx, val_idx)
    706                 res = []
    707                 for r in results:
--> 708                     res.extend(r.result())
    709         return res
    710 

E:\ml\lib\concurrent\futures\_base.py in result(self, timeout)
    444                     raise CancelledError()
    445                 elif self._state == FINISHED:
--> 446                     return self.__get_result()
    447                 else:
    448                     raise TimeoutError()

E:\ml\lib\concurrent\futures\_base.py in __get_result(self)
    389         if self._exception:
    390             try:
--> 391                 raise self._exception
    392             finally:
    393                 # Break a reference cycle with the exception in self._exception

SystemExit: None

**Comment by ZhangTP1996** [comment]
It seems that the real problem is 
```
Traceback (most recent call last):
File "E:\ml\lib\site-packages\openfe\openfe.py", line 676, in _calculate_and_evaluate_multiprocess
init_metric = self.get_init_metric(val_init, val_y)
File "E:\ml\lib\site-packages\openfe\openfe.py", line 545, in get_init_metric
init_metric = log_loss(label, scipy.special.softmax(pred, axis=1))
File "E:\ml\lib\site-packages\sklearn\metrics_classification.py", line 2424, in log_loss
raise ValueError(
ValueError: y_true and y_pred contain different number of classes 9, 10. Please provide the true labels explicitly through the labels argument. Classes found in y_true: [ 1 3 4 5 6 7 8 9 10]
```

But I cannot identify what causes this problem since stratified train test split has been used. Could you please provide the code and dataset to reproduce this bug?

**Comment by ruler611** [comment]
The dataset is a ten-category data, the classification label y has a total of 10 categories (1,2,3,...10) The bug is very strange, once there was no error reported, it can ran down normally, but recently it always reported this bug

**Comment by ZhangTP1996** [comment]
Sorry for the late reply. I think I have found the reason. We need to pass in the label explictly when calculating the log loss. Otherwise it may report error when the number of samples in the class is small. 
`log_loss(label, scipy.special.softmax(pred, axis=1), labels=list(range(pred.shape[1])))`
The latest version of OpenFE should address your problem.

**Comment by soul44d4** [comment]
> Sorry for the late reply. I think I have found the reason. We need to pass in the label explictly when calculating the log loss. Otherwise it may report error when the number of samples in the class is small. `log_loss(label, scipy.special.softmax(pred, axis=1), labels=list(range(pred.shape[1])))` The latest version of OpenFE should address your problem.

Thanks for reply. So you are meaning, when we pass a small dateset into the function, it might report error in the old version?

**Comment by ZhangTP1996** [comment]
> > Sorry for the late reply. I think I have found the reason. We need to pass in the label explictly when calculating the log loss. Otherwise it may report error when the number of samples in the class is small. `log_loss(label, scipy.special.softmax(pred, axis=1), labels=list(range(pred.shape[1])))` The latest version of OpenFE should address your problem.
> 
> Thanks for reply. So you are meaning, when we pass a small dateset into the function, it might report error in the old version?

Regression problems should be fine. It might report errors on small classification datasets in the old version.
