### ISSUE TITLE
Can I use other models

### ISSUE THREAD

**Issue by huangqingyi-code** [IIIS-Li-Group/OpenFE#15]
hello,I have two questions. I hope you can help me answer them.
1.In stage1 and stage2 select ,can I use other models ,such as xgboost,rf,adaboost?
2.My base model is LR. Can I use openfe to generate features?

**Comment by ZhangTP1996** [comment]
1. Other models are applicable but not yet supported by OpenFE.
2. Yes, of course.

**Comment by huangqingyi-code** [comment]
1.用lightgbm在stage1中评估特征中用到了init_score，和eval_init_score两个接口，其他模型好像没有啊。我有个疑问：下游模型如果是RF，在openfe中把评估模型换成RF效果是否会更好？
2.用lightgbm树模型筛选出来的特征给线性模型LR也能有效果？
3.还有个疑问采用feature_boosting的时候算ini_score使用所有特征的，但后面评估特征的时候使用单个特征训练lgb，然后算差值，为什么进行这样比较？

**Comment by ZhangTP1996** [comment]
> 

1. xgboost是有的，只不过名字不叫init_score。rf我不太清楚，不过也可以换种方法写成类似的效果。换成和下游模型一样的有可能会效果更好，但是我没做过对应实验。
2. 如果新特征的效果有线性的成分（经验上来看这个也比较常见）是会有效果的，当然本身搜索的时候就用LR可能会更好
3. 用所有特征是为了去除掉所有特征的效果，之后用单个特征是为了看这单个特征相对于所有特征的额外效果。
