### ISSUE TITLE
math expressions of features

### ISSUE THREAD

**Issue by tanguoming** [IIIS-Li-Group/OpenFE#16]
As I'd like to use new generated features for further clustering or model interpretability, their math expressions are needed. How can I simply fetch math expressions of new features? thanks.

(Model interpretability is important. People won't use those features they don't know why)

**Comment by ZhangTP1996** [comment]
Please refer to line 39-41 in the example code [https://github.com/IIIS-Li-Group/OpenFE/blob/master/examples/california_housing.py](url) to see how to print the math expressions of the new features.
