### ISSUE TITLE
Reporting Bug : subsampled train_index and test_index can have duplicated values

### ISSUE THREAD

**Issue by InPatience** [IIIS-Li-Group/OpenFE#21]
Hi, Tianpin. During my recent test on classification problem using a relatively small dataset, an error has been raised in the stage_1_select process. 

```
Traceback (most recent call last):
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/openfe/openfe.py", line 589, in _evaluate
    gbm.fit(train_x, train_y, init_score=train_init,
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/sklearn.py", line 967, in fit
    super().fit(X, _y, sample_weight=sample_weight, init_score=init_score, eval_set=valid_sets,
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/sklearn.py", line 748, in fit
    self._Booster = train(
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/engine.py", line 271, in train
    booster = Booster(params=params, train_set=train_set)
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/basic.py", line 2605, in __init__
    train_set.construct()
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/basic.py", line 1815, in construct
    self._lazy_init(self.data, label=self.label,
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/basic.py", line 1557, in _lazy_init
    self.set_label(label)
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/basic.py", line 2164, in set_label
    self.set_field('label', label)
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/basic.py", line 1993, in set_field
    _safe_call(_LIB.LGBM_DatasetSetField(
  File "/mnt/lhc/anaconda3/lib/python3.8/site-packages/lightgbm/basic.py", line 125, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Length of label is not same with #data
```

This is caused by the sampling function `_subsample`, which can generate subsamples with duplicated index. Specifically, at line from 458 to 461,
```
        train_index_samples = _subsample(self.train_index, self.n_data_blocks)
        val_index_samples = _subsample(self.val_index, self.n_data_blocks)
        idx = 0
        train_idx = train_index_samples[idx]
        val_idx = val_index_samples[idx]
```
`train_idx `and `val_idx ` may have some index both contained by each other. And this can cause an error. 

In `_calculate_and_evaluate_multiprocess` at line 670, by slicing dataframe like this :
```
        data_temp = data.loc[train_idx + val_idx]
```
data_temp will have a dupliceted index. Thus, `train_x = pd.DataFrame(candidate_feature.data.loc[train_y.index])` will lead to  duplicated index in `train_x` and `lightgbm.basic.LightGBMError: Length of label is not same with #data`

**Comment by ZhangTP1996** [comment]
Thank you for reporting this bug! I think the only reason that `_subsample` generate subsamples with duplicated index is because `train_idx` and `val_idx` have duplicated index, which is because of the duplicated index in the input `data`. Could you please check whether there is duplicated index in the input `data`?

**Comment by InPatience** [comment]
I encountered this problem when I reset and drop the index of my input data, just as this way
`data_set_test = data_set_test.reset_index(drop=True)`. So I suppose there should not be duplicated index in my input data.

**Comment by InPatience** [comment]
My previous expression could be ambiguous. The problem is a index label can be simultaneously included by `train_idx `and `val_idx` since the two subsample procedures are independent. 

For instance,  suppose the `train_idx ` is ['a','b','c'] and the `val_idx` is ['c', 'd','e']. Then dataframe slicing by `data_temp = data.loc[train_idx + val_idx]` will generate a dataframe with index ['a','b','c', 'c', 'd','e'], a dupplicated-index dataframe.

**Comment by ZhangTP1996** [comment]
According to the code logic I cannot see why this happens... If the `train_idx` and `val_idx` are determined inside `openfe`, we use `train_test_split` of sklearn to split the `data` into train set and validation set, which should not have duplicated index (if the `data` does not have duplicated index).

**Comment by InPatience** [comment]
Thank you so much for your response. Yes, you are right. The problem is caused by my misuse on params `train_index` and `val_index` during the fitting process. I really appreciate your help!

**Comment by ZhangTP1996** [comment]
No problem at all. Let me know if you need anything else.
