### ISSUE TITLE
a question of transform function

### ISSUE THREAD

**Issue by Lycxder** [IIIS-Li-Group/OpenFE#22]
Hello, I appreciate your wonderful work! I have a question about `transform()`. You said in api document that train and test data need to be transformed together because there are global operators such as ‘GroupByThenMean’. I have multiple test sets and one training set, if I call` transform ()` using the training set and different test sets several times, are the transformed training sets the same? If not, how can I make them identical? Thanks a lot, waiting for you reply!

**Comment by ZhangTP1996** [comment]
I am wondering why the training sets should be identical, and understanding the reasons behind it would allow me to provide more help. I have two potential solutions: the first is to concatenate the test sets together, transform them once, and then separate them again afterwards. The second solution is to simply use one of the transformed training sets.

**Comment by Lycxder** [comment]
Because I want to evaluate on all test sets using one trained model to make performance comparable. Thanks for your advise, I will concatenate test sets and make transformation.
