### ISSUE TITLE
is it normal to be so slow？

### ISSUE THREAD

**Issue by Richard-LYF** [IIIS-Li-Group/OpenFE#26]
![2b2be996f4ffb08751f1b583d98cec1](https://user-images.githubusercontent.com/48831875/233280287-4b476dba-765b-4004-916f-3a6cbd63dda5.png)
I have been wating for around ten mins, and there is no respond, is it normal?
So generally, how long should we wait?
my X.shape is (49810800, 5)

**Comment by ZhangTP1996** [comment]
The number of sample is too large. It is recommended to perform subsampling or follow the guide in https://openfe-document.readthedocs.io/en/latest/parameter_tuning.html for faster speed.

**Comment by Richard-LYF** [comment]
so how many samples are proper?

**Comment by ZhangTP1996** [comment]
_> so how many samples are proper?

The answer to this question is heuristic and depends on both your available computing resources and desired running time. You may first try one million samples to see whether feature generation helps.
