### ISSUE TITLE
Missing Value Filling Problem

### ISSUE THREAD

**Issue by HliFuture** [IIIS-Li-Group/OpenFE#27]
Say I have two columns A and B, and openFE will calculate a column C = A * B. But I found that when a record of column A or B is null, the result of this record of Column C will be filled by 0. Is 0 a default fillna value? Can I change this default or leave this record of column C null if A or B is null?

**Comment by ZhangTP1996** [comment]
It seems that this problem is due to the `fillna` operation in the transformation process. We have removed `fillna` and the latest code in the github or the latest package version (0.0.12) should resolve your problem.

**Comment by HliFuture** [comment]
I upgrade the package, it fixed the issue. Thanks for quickly help.
