### ISSUE TITLE
How to reproduce table 3 (main results table)?

### ISSUE THREAD

**Issue by junweima** [IIIS-Li-Group/OpenFE#28]
Thanks for sharing this interesting work!

I have 2 questions:

1. Are there download links to the datasets used in Table 3? Specifically I cannot find datasets such as `Microsoft`, `Telecom`, `Broken Machine` etc online for download
2. Is there code associated with it to reproduce table 3?

![image](https://github.com/IIIS-Li-Group/OpenFE/assets/5514321/71ac9b09-4172-40f2-aac0-54e5e5cd82cd)

Thanks!

**Comment by ZhangTP1996** [comment]
Thank you for your interest in our work! The datasets are available at https://www.dropbox.com/s/8tj5ln7wz1r9arc/data.zip?dl=0.  I am still working on reorganizing the codes for the baseline methods and writing the documentation for better reproduction. I am planning to release the codes around 6.25 (as I am now rushing for another conference QAQ). Sorry for any inconvenience this may cause.

**Comment by ZhangTP1996** [comment]
The code and datasets are now available in this new repository: https://github.com/ZhangTP1996/OpenFE_reproduce
