### ISSUE TITLE
import error, after pip install openfe

### ISSUE THREAD

**Issue by yjp01** [IIIS-Li-Group/OpenFE#3]
I have installed the package using pip, but when import openfe, get a error.
The error is: 
OSError: dlopen(/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
  Referenced from: '/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so'
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file).
My compute Is MacBook Pro 14
python version is 3.913
Looking forward to your reply

**Comment by ZhangTP1996** [comment]
> Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'

It seems that the problem in on lightgbm. Could you please try `brew install libomp`? (The solution is from https://www.jianshu.com/p/3dec0e1d12dc)

**Comment by ZhangTP1996** [comment]
> I have installed the package using pip, but when import openfe, get a error. The error is: OSError: dlopen(/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib' Referenced from: '/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so' Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file). My compute Is MacBook Pro 14 python version is 3.913 Looking forward to your reply

Another solution is to run the code in a conda environment instead of using the python installed in mac by default. For example:
```
conda create -n OpenFE python=3.8
conda activate OpenFE
pip install openfe
```

**Comment by yjp01** [comment]
> > Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib'
> 
> It seems that the problem in on lightgbm. Could you please try `brew install libomp`? (The solution is from https://www.jianshu.com/p/3dec0e1d12dc)

I have tried this solution, but the problem is not solved

**Comment by yjp01** [comment]
> > I have installed the package using pip, but when import openfe, get a error. The error is: OSError: dlopen(/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib' Referenced from: '/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so' Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file). My compute Is MacBook Pro 14 python version is 3.913 Looking forward to your reply
> 
> Another solution is to run the code in a conda environment instead of using the python installed in mac by default. For example:
> 
> ```
> conda create -n OpenFE python=3.8
> conda activate OpenFE
> pip install openfe
> ```

**Comment by yjp01** [comment]
> > I have installed the package using pip, but when import openfe, get a error. The error is: OSError: dlopen(/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: '/usr/local/opt/libomp/lib/libomp.dylib' Referenced from: '/Users/yuanjunping/opt/anaconda3/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so' Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file). My compute Is MacBook Pro 14 python version is 3.913 Looking forward to your reply
> 
> Another solution is to run the code in a conda environment instead of using the python installed in mac by default. For example:
> 
> ```
> conda create -n OpenFE python=3.8
> conda activate OpenFE
> pip install openfe
> ```

hai shi bu xing, tong yang de wen ti. wo gan jue ke neng shi arm xin pian de wen ti. thanks, wo di yi ci ti wen, ni neng zhe me ji shi hui fu, hen kai xin.

**Comment by ZhangTP1996** [comment]
> 

You are welcome! I ask my friend who also uses mac for help. He said the problem is solved using the conda enviroment in his mac. It is such a pity that this method does not work in your case.
