### ISSUE TITLE
How do I know the construction method of each newly generated feature

### ISSUE THREAD

**Issue by kjdsfbchkadwbcuiwbcfiw** [IIIS-Li-Group/OpenFE#34]
Openfe can generate a large number of features, but how do I know how each feature is constructed?

**Comment by yczju** [comment]
You can just use the following code to get the construction of each feature:
```
from openfe import tree_to_formula
features = ofe.fit(X_train, Y_train)
feature_list = [tree_to_formula(feature) for feature in features]
```
feature_list contains all original feature combinations.

**Comment by kjdsfbchkadwbcuiwbcfiw** [comment]
Great! Thank you
