### ISSUE TITLE
lightgbm.basic.LightGBMError: Length of labels differs from the length of #data

### ISSUE THREAD

**Issue by MatthewZhuang** [IIIS-Li-Group/OpenFE#45]
when i run the method , it raise the error while the train data and label data is the same length

**Comment by MatthewZhuang** [comment]
Thanks for reply, i will have a try.

**Comment by FluidGrace** [comment]
pandas.concat() was culprit in my case, could .fit() have problem with concatenated dataframes? Combining data without pandas and then converting to dataframe in the end worked for me.

**Comment by ZhangTP1996** [comment]
Concatenatd dataframes are just dataframes. There might be some  other
issues such as duplicated index or multiindex.

FluidGrace ***@***.***> 于2024年5月25日周六 04:55写道：
