### ISSUE TITLE
need at least one array to concatenate

### ISSUE THREAD

**Issue by gaozhanfire** [IIIS-Li-Group/OpenFE#5]
I run the sample code on my own dataset,the error I get as below
![image](https://user-images.githubusercontent.com/34774408/205281519-58c164a3-14cd-43b8-b66f-2dcf626cd9e7.png)

**Comment by ZhangTP1996** [comment]
This means that none of the candidate features pass the stage1 selection. The most probable reason is poor hyperparameter settings?  Could you please tell me what hyperparameters are you using?
