### ISSUE TITLE
Running the code in my own dataset with error

### ISSUE THREAD

**Issue by ZhongChu16** [IIIS-Li-Group/OpenFE#6]
Hi Today I try to run the code in my own dataset, the data has 31 features and they are all numbers.
The task is regression.
When I run the code, I have the following issues
The number of candidate features is 9329
  6%|▋         | 2/32 [00:01<00:20,  1.46it/s]
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?324c158e-26aa-4417-80bb-8ad90f7465de)
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\Users\Zhong\AppData\Local\Programs\Python\Python310\lib\site-packages\openfe\openfe.py", line 662, in _calculate_and_evaluate_multiprocess
    score = self._evaluate(candidate_feature, train_y, val_y, train_init, val_init, init_metric)
  File "c:\Users\Zhong\AppData\Local\Programs\Python\Python310\lib\site-packages\openfe\openfe.py", line 595, in _evaluate
    return score
UnboundLocalError: local variable 'score' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Zhong\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "c:\Users\Zhong\AppData\Local\Programs\Python\Python310\lib\site-packages\openfe\openfe.py", line 667, in _calculate_and_evaluate_multiprocess
    exit()
  File "c:\Users\Zhong\AppData\Local\Programs\Python\Python310\lib\_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None
"""

The above exception was the direct cause of the following exception:
...
    170 if isinstance(error, str):
    171     error = AssertionError(error)
--> 172 raise error

AssertionError:

**Comment by ZhangTP1996** [comment]
The code should print something that shows what the error is. Could you provide the dataset and the code for replicating this error?

**Comment by ZhongChu16** [comment]
I have sent the code and dataset to your Tsinghua email
Looking forward to your reply

**Comment by ZhangTP1996** [comment]
> I have sent the code and dataset to your Tsinghua email Looking forward to your reply

The main reason is that LightGBM does not support special JSON character in feature name, such as '('. A simple solution is to rename the feature names
```
import re
train_x = train_x.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))
n_jobs = 8
ofe = openfe()
features = ofe.fit(data=train_x, label=train_y, task= 'regression',n_jobs=n_jobs)
```

**Comment by ZhangTP1996** [comment]
> I have sent the code and dataset to your Tsinghua email Looking forward to your reply

The actual error is the following:
lightgbm.basic.LightGBMError: Do not support special JSON characters in feature name.

I'm not sure why this error is not printed in jupyter notebook.
