### ISSUE TITLE
local variable 'score' referenced before assignment

### ISSUE THREAD

**Issue by ccuixun9929** [IIIS-Li-Group/OpenFE#8]
Hello,I have the following problem when i  use it：
\openfe\openfe.py", line 662, in _calculate_and_evaluate_multiprocess
\openfe\openfe.py", line 595, in _evaluate return score
UnboundLocalError: local variable 'score' referenced before assignment
How can I solve it
thank you

**Comment by ZhangTP1996** [comment]
> Hello,I have the following problem when i use it： \openfe\openfe.py", line 662, in _calculate_and_evaluate_multiprocess \openfe\openfe.py", line 595, in _evaluate return score UnboundLocalError: local variable 'score' referenced before assignment How can I solve it thank you

Could you please provide the code and datasets so that I can reproduce this bug?
